name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Workaround for upload-artifact@v3 error
      - name: Dummy upload step to prefetch artifact action
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Or 'dist' or 'build' as per your project

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
